USING KERAS

In [58]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [25]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])


In [36]:
model = Sequential([
    Dense(8, activation='tanh', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])


In [37]:
model.compile(
    optimizer=Adam(learning_rate=0.1),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [38]:
history = model.fit(
    X, y,
    epochs=1000,
    verbose=0
)


In [39]:
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", accuracy)


Loss: 3.7963836803101e-05
Accuracy: 1.0


In [40]:
predictions = model.predict(X)
print("Predicted Outputs:")
print(np.round(predictions))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Predicted Outputs:
[[0.]
 [1.]
 [1.]
 [0.]]


THIS IS USING PYTORCH

In [41]:
import torch
import torch.nn as nn
import torch.optim as optim

In [42]:
X_torch = torch.tensor(X, dtype=torch.float32)
y_torch = torch.tensor(y, dtype=torch.float32)

In [44]:
class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 2)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.tanh(self.hidden(x))
        x = torch.sigmoid(self.output(x))
        return x
model = XORNet()

In [45]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)


In [47]:
for epoch in range(500):
    optimizer.zero_grad()
    outputs = model(X_torch)
    loss = criterion(outputs, y_torch)
    loss.backward()
    optimizer.step()


In [51]:
with torch.no_grad():
    outputs = model(X_torch)
    predictions = (outputs >= 0.5).float()
    accuracy = (predictions == y_torch).sum().item() / y_torch.size(0)

print("Accuracy:", accuracy)
print("Predictions:")
print(predictions)

Accuracy: 1.0
Predictions:
tensor([[0.],
        [1.],
        [1.],
        [0.]])


USING TENSERFLOW

In [52]:
import tensorflow as tf

X_tf = tf.constant(X, dtype=tf.float32)
y_tf = tf.constant(y, dtype=tf.float32)

W1 = tf.Variable(tf.random.normal([2,2]))
b1 = tf.Variable(tf.zeros([2]))

W2 = tf.Variable(tf.random.normal([2,1]))
b2 = tf.Variable(tf.zeros([1]))


In [53]:
def model(x):
    h = tf.tanh(tf.matmul(x, W1) + b1)
    out = tf.sigmoid(tf.matmul(h, W2) + b2)
    return out


In [54]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.1)


In [55]:
for epoch in range(1000):
    with tf.GradientTape() as tape:
        predictions = model(X_tf)
        loss = loss_fn(y_tf, predictions)

    gradients = tape.gradient(loss, [W1, b1, W2, b2])
    optimizer.apply_gradients(zip(gradients, [W1, b1, W2, b2]))


In [57]:
predictions = model(X_tf)
predicted_classes = tf.cast(predictions >= 0.5, tf.float32)

accuracy = tf.reduce_mean(
    tf.cast(tf.equal(predicted_classes, y_tf), tf.float32)
)

print("Accuracy:", accuracy.numpy())
print("Predictions:")
print(predicted_classes.numpy())

Accuracy: 1.0
Predictions:
[[0.]
 [1.]
 [1.]
 [0.]]
